export const CAMPAIGN = "june-2027-v1";
export const covers = [
  [
    "electric-dreams",
    "Electric dreams",
    "A little louder. A little you.",
    "#d9ff43",
    "#172ad0",
    "DREAM / BIGGER.",
  ],
  [
    "slow-sundays",
    "Slow Sundays",
    "Leave a little room for nothing.",
    "#f2a9d0",
    "#762c49",
    "SLOW / DAYS.",
  ],
  [
    "blue-hour",
    "Blue hour",
    "For the beautiful in-between.",
    "#1733bc",
    "#c2ddff",
    "BLUE / HOUR",
  ],
  [
    "main-character",
    "Main character",
    "A year that has your name on it.",
    "#ff7045",
    "#431622",
    "MAKE / IT / YOURS.",
  ],
  [
    "fresh-start",
    "Fresh start",
    "Every page is a possibility.",
    "#174e43",
    "#d8f376",
    "BEGIN / AGAIN.",
  ],
  [
    "little-wonders",
    "Little wonders",
    "Notice the small, good things.",
    "#f7d255",
    "#8d3826",
    "OH, / WHAT / A DAY.",
  ],
  [
    "after-hours",
    "After hours",
    "Ideas that keep you up.",
    "#271340",
    "#e7a8fd",
    "AFTER / HOURS.",
  ],
  [
    "daydream-club",
    "Daydream club",
    "A place for your what-ifs.",
    "#b1e3ec",
    "#17465e",
    "DAY / DREAM / CLUB",
  ],
  [
    "wild-thoughts",
    "Wild thoughts",
    "Go where your curiosity goes.",
    "#e72f51",
    "#ffd7a8",
    "STAY / CURIOUS.",
  ],
  [
    "soft-focus",
    "Soft focus",
    "Less rush. More feeling.",
    "#ecc1ad",
    "#644665",
    "SOFT / FOCUS",
  ],
  [
    "good-energy",
    "Good energy",
    "Make space for the good stuff.",
    "#adcf46",
    "#21403b",
    "GOOD / THINGS / AHEAD.",
  ],
  [
    "new-chapter",
    "New chapter",
    "The next chapter is yours.",
    "#eeeae1",
    "#182dc4",
    "HERE / WE / GO.",
  ],
].map(([id, name, caption, bg, ink, title], i) => ({
  id,
  name,
  caption,
  bg,
  ink,
  title,
  image: `/covers/${id}.svg`,
  number: i + 1,
}));
